AWSTemplateFormatVersion: "2010-09-09"
Description: "IceML env"
Resources: 

  MyEC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-3bfab942"
      KeyName: "iceml_kp"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref icemlSubnet
          GroupSet:
            - !Ref InstanceSecurityGroup

  ICEMLVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.207.16.0/21
      EnableDnsSupport: True
      EnableDnsHostnames: False
      InstanceTenancy: default

  icemlSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ICEMLVPC
      CidrBlock: 10.207.16.0/24
      AvailabilityZone: "eu-west-1a"

  icemlSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ICEMLVPC
      CidrBlock: 10.207.17.0/24
      AvailabilityZone: "eu-west-1b"

  ICEMLGW:
    Type: "AWS::EC2::InternetGateway"

  VPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId:
        Ref: ICEMLGW
      VpcId:
        Ref: ICEMLVPC

  PublicNetRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: ICEMLVPC

  PublicRoute:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: ICEMLGW
      RouteTableId:
        Ref: PublicNetRouteTable

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access and HTTP access on the configured port
      VpcId: !Ref ICEMLVPC
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0' 
        - IpProtocol: 'tcp'
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: '0.0.0.0/0'

  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open database for access
      VpcId: !Ref ICEMLVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '5432'
        ToPort: '5432'
        SourceSecurityGroupId: !Ref InstanceSecurityGroup

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: icemldb
      Engine: postgres
      MasterUsername: iceml
      MasterUserPassword: WinterNavigation
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 10
      VPCSecurityGroups:
      - !GetAtt DBEC2SecurityGroup.GroupId
      DBSubnetGroupName: !Ref IcemlRdsSubnetGroup

  IcemlRdsSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: CloudFormation managed DB subnet group.
        SubnetIds:
          - !Ref icemlSubnet
          - !Ref icemlSubnet2
